from pyspark.sql.types import (
    StructType, StructField, StringType, DoubleType,
    IntegerType, BooleanType, ArrayType
)


# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
# SCHEMAS â€” StructType for spark.read.schema()
# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

_payment_schema = StructType([
    StructField("PayId",         StringType(), True),
    StructField("PaymentType",   StringType(), True),
    StructField("PaymentRemark", StringType(), True),
    StructField("Amount",        DoubleType(), True),
])

_reservation_ref_schema = StructType([
    StructField("ReservationKey",    StringType(), True),
    StructField("Reservationnumber", StringType(), True),
    StructField("Amount",            DoubleType(), True),
])

entity_schema_config = {

    "baskets": StructType([
        StructField("BasketConfirmed",      StringType(),                       True),
        StructField("BasketNumber",         StringType(),                       True),
        StructField("BasketKey",            StringType(),                       True),
        StructField("ExternalBasketNumber", StringType(),                       True),
        StructField("ExternalInvoiceId",    StringType(),                       True),
        StructField("PosFirstName",         StringType(),                       True),
        StructField("PosMiddleName",        StringType(),                       True),
        StructField("PosLastName",          StringType(),                       True),
        StructField("PosName",              StringType(),                       True),
        StructField("PosGroupName",         StringType(),                       True),
        StructField("Payments",             ArrayType(_payment_schema),         True),
        StructField("Reservations",         ArrayType(_reservation_ref_schema), True),
        StructField("Cancellations",        ArrayType(StringType()),            True),
        StructField("PartialCancellation",  ArrayType(StringType()),            True),
        StructField("Contact",              StringType(),                       True),
    ]),

    "ticket_scans": StructType([
        StructField("ScanId",                      IntegerType(),  True),
        StructField("TicketCode",                   StringType(),  True),
        StructField("ScanGroupName",                StringType(),  True),
        StructField("DeviceID",                     StringType(),  True),
        StructField("Type",                         StringType(),  True),
        StructField("ReservationKey",               StringType(),  True),
        StructField("SubscriptionKey",              StringType(),  True),
        StructField("SubscriptionProductKey",       StringType(),  True),
        StructField("ScanDate",                     StringType(),  True),
        StructField("SubscriptionTemplateKey",      StringType(),  True),
        StructField("ProductName",                  StringType(),  True),
        StructField("InternalId",                   StringType(),  True),
        StructField("ProductInternalId",            StringType(),  True),
        StructField("Name",                         StringType(),  True),
        StructField("EMail",                        StringType(),  True),
        StructField("Street",                       StringType(),  True),
        StructField("HouseNumber",                  StringType(),  True),
        StructField("PostalCode",                   StringType(),  True),
        StructField("CityName",                     StringType(),  True),
        StructField("CountryName",                  StringType(),  True),
        StructField("Lat",                          DoubleType(),  True),
        StructField("Lon",                          DoubleType(),  True),
        StructField("EventKey",                     StringType(),  True),
        StructField("PerformanceKey",               StringType(),  True),
        StructField("PerformanceSectionKey",        StringType(),  True),
        StructField("ValidFrom",                    StringType(),  True),
        StructField("ValidTo",                      StringType(),  True),
        StructField("CompanyName",                  StringType(),  True),
        StructField("FirstName",                    StringType(),  True),
        StructField("Middle",                       StringType(),  True),
        StructField("LastName",                     StringType(),  True),
        StructField("PhoneNumber",                  StringType(),  True),
        StructField("ReservationNumber",            StringType(),  True),
        StructField("PriceKey",                     StringType(),  True),
        StructField("Price",                        DoubleType(),  True),
        StructField("OriginalPrice",                DoubleType(),  True),
        StructField("BuyingPrice",                  DoubleType(),  True),
        StructField("ExternalID",                   StringType(),  True),
        StructField("ExternalReservationNumber",    StringType(),  True),
        StructField("ExtraInfo1",                   StringType(),  True),
        StructField("ExtraInfo2",                   StringType(),  True),
        StructField("ExtraInfo3",                   StringType(),  True),
        StructField("TestPayment",                  BooleanType(), True),
        StructField("ReceiveNewsletter",            BooleanType(), True),
    ]),

    "sold_tickets": StructType([
        StructField("EventKey",                                 StringType(),  True),
        StructField("Type",                                     StringType(),  True),
        StructField("ReservationKey",                           StringType(),  True),
        StructField("PerformanceKey",                           StringType(),  True),
        StructField("PerformanceSectionKey",                    StringType(),  True),
        StructField("ProductName",                              StringType(),  True),
        StructField("SaleDate",                                 StringType(),  True),
        StructField("TotalPrice",                               DoubleType(),  True),
        StructField("Price",                                    DoubleType(),  True),
        StructField("OriginalPrice",                            DoubleType(),  True),
        StructField("BuyingPrice",                              DoubleType(),  True),
        StructField("NrOfSeats",                                IntegerType(), True),
        StructField("Channel",                                  StringType(),  True),
        StructField("ContactHolderKey",                         StringType(),  True),
        StructField("Name",                                     StringType(),  True),
        StructField("EMail",                                    StringType(),  True),
        StructField("Street",                                   StringType(),  True),
        StructField("HouseNumber",                              StringType(),  True),
        StructField("PostalCode",                               StringType(),  True),
        StructField("CityName",                                 StringType(),  True),
        StructField("CountryName",                              StringType(),  True),
        StructField("Lat",                                      DoubleType(),  True),
        StructField("Lon",                                      DoubleType(),  True),
        StructField("ValidFrom",                                StringType(),  True),
        StructField("ValidTo",                                  StringType(),  True),
        StructField("CompanyName",                              StringType(),  True),
        StructField("FirstName",                                StringType(),  True),
        StructField("Middle",                                   StringType(),  True),
        StructField("LastName",                                 StringType(),  True),
        StructField("PhoneNumber",                              StringType(),  True),
        StructField("ReceiveNewsLetter",                        BooleanType(), True),
        StructField("PaymentMethod",                            StringType(),  True),
        StructField("BrancheID",                                StringType(),  True),
        StructField("CancelDate",                               StringType(),  True),
        StructField("ReservationNumber",                        StringType(),  True),
        StructField("Language",                                 StringType(),  True),
        StructField("SalesChannel",                             StringType(),  True),
        StructField("ResellerName",                             StringType(),  True),
        StructField("PriceKey",                                 StringType(),  True),
        StructField("LanguageCode",                             StringType(),  True),
        StructField("TicketCode",                               StringType(),  True),
        StructField("CapacityDate",                             StringType(),  True),
        StructField("CapacityStartTimeMinutesAfterMidnight",    IntegerType(), True),
        StructField("CapacityEndTimeMinutesAfterMidnight",      IntegerType(), True),
        StructField("CapacityStartDate",                        StringType(),  True),
        StructField("CapacityStartTime",                        StringType(),  True),
        StructField("CapacityEndTime",                          StringType(),  True),
        StructField("PosGroupTitle",                            StringType(),  True),
        StructField("PosTitle",                                 StringType(),  True),
        StructField("PosContact",                               StringType(),  True),
        StructField("ExternalReservationNumber",                StringType(),  True),
        StructField("ExternalID",                               StringType(),  True),
        StructField("ExtraInfo1",                               StringType(),  True),
        StructField("ExtraInfo2",                               StringType(),  True),
        StructField("ExtraInfo3",                               StringType(),  True),
        StructField("TestPayment",                              BooleanType(), True),
        StructField("ConfirmedDate",                            StringType(),  True),
        StructField("VatNumber",                                StringType(),  True),
        StructField("VatLow",                                   DoubleType(),  True),
        StructField("VatMiddle",                                DoubleType(),  True),
        StructField("VatHigh",                                  DoubleType(),  True),
        StructField("AmountExVatLow",                           DoubleType(),  True),
        StructField("AmountExVatMiddle",                        DoubleType(),  True),
        StructField("AmountExVatHigh",                          DoubleType(),  True),
        StructField("CashBooking",                              BooleanType(), True),
    ]),

    "sold_subscriptions": StructType([
        StructField("SubscriptionKey",              StringType(),  True),
        StructField("Type",                         StringType(),  True),
        StructField("ReservationKey",               StringType(),  True),
        StructField("SubscriptionTemplateKey",      StringType(),  True),
        StructField("ProductName",                  StringType(),  True),
        StructField("SaleDate",                     StringType(),  True),
        StructField("Price",                        DoubleType(),  True),
        StructField("Renewal",                      BooleanType(), True),
        StructField("Channel",                      StringType(),  True),
        StructField("SubscriptionHolderKey",        StringType(),  True),
        StructField("InternalId",                   StringType(),  True),
        StructField("Name",                         StringType(),  True),
        StructField("EMail",                        StringType(),  True),
        StructField("Street",                       StringType(),  True),
        StructField("HouseNumber",                  StringType(),  True),
        StructField("PostalCode",                   StringType(),  True),
        StructField("CityName",                     StringType(),  True),
        StructField("CountryName",                  StringType(),  True),
        StructField("Lat",                          DoubleType(),  True),
        StructField("Lon",                          DoubleType(),  True),
        StructField("ValidFrom",                    StringType(),  True),
        StructField("ValidTo",                      StringType(),  True),
        StructField("CompanyName",                  StringType(),  True),
        StructField("FirstName",                    StringType(),  True),
        StructField("Middle",                       StringType(),  True),
        StructField("LastName",                     StringType(),  True),
        StructField("PhoneNumber",                  StringType(),  True),
        StructField("ReceiveNewsLetter",            BooleanType(), True),
        StructField("PaymentMethod",                StringType(),  True),
        StructField("NrOfSubscriptionProducts",     IntegerType(), True),
        StructField("CancelDate",                   StringType(),  True),
        StructField("ReservationNumber",            StringType(),  True),
        StructField("Language",                     StringType(),  True),
        StructField("LanguageCode",                 StringType(),  True),
        StructField("LoyaltyLevel",                 StringType(),  True),
        StructField("PosGroupTitle",                StringType(),  True),
        StructField("PosTitle",                     StringType(),  True),
        StructField("PosContact",                   StringType(),  True),
        StructField("ExternalID",                   StringType(),  True),
        StructField("TestPayment",                  BooleanType(), True),
        StructField("Gender",                       StringType(),  True),
        StructField("BirthDate",                    StringType(),  True),
    ]),

    "cancellations": StructType([
        StructField("ReservationKey",               StringType(),  True),
        StructField("ReservationNumber",            StringType(),  True),
        StructField("ExternalReservationNumber",    StringType(),  True),
        StructField("CancelDate",                   StringType(),  True),
        StructField("Price",                        DoubleType(),  True),
        StructField("OriginalPrice",                DoubleType(),  True),
        StructField("NrOfSeats",                    IntegerType(), True),
        StructField("ValidFrom",                    StringType(),  True),
        StructField("ValidTo",                      StringType(),  True),
    ]),
}
